// Code generated by protoc-gen-go.
// source: bacs/problem/single/intermediate.proto
// DO NOT EDIT!

/*
Package single is a generated protocol buffer package.

It is generated from these files:
	bacs/problem/single/intermediate.proto
	bacs/problem/single/problem.proto
	bacs/problem/single/result.proto
	bacs/problem/single/task.proto

It has these top-level messages:
	IntermediateResult
	ProblemExtension
	Tests
	ProfileExtension
	Dependency
	TestGroup
	Result
	TestGroupResult
	TestResult
	JudgeResult
	FileResult
	Task
*/
package single

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type IntermediateResult_State int32

const (
	IntermediateResult_UNKNOWN     IntermediateResult_State = 0
	IntermediateResult_INITIALIZED IntermediateResult_State = 1
	IntermediateResult_BUILDING    IntermediateResult_State = 2
	IntermediateResult_TESTING     IntermediateResult_State = 3
)

var IntermediateResult_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "INITIALIZED",
	2: "BUILDING",
	3: "TESTING",
}
var IntermediateResult_State_value = map[string]int32{
	"UNKNOWN":     0,
	"INITIALIZED": 1,
	"BUILDING":    2,
	"TESTING":     3,
}

func (x IntermediateResult_State) String() string {
	return proto.EnumName(IntermediateResult_State_name, int32(x))
}

type IntermediateResult struct {
	State       IntermediateResult_State `protobuf:"varint,1,opt,name=state,enum=bacs.problem.single.IntermediateResult_State" json:"state,omitempty"`
	TestGroupId string                   `protobuf:"bytes,2,opt,name=test_group_id" json:"test_group_id,omitempty"`
	TestId      string                   `protobuf:"bytes,3,opt,name=test_id" json:"test_id,omitempty"`
}

func (m *IntermediateResult) Reset()         { *m = IntermediateResult{} }
func (m *IntermediateResult) String() string { return proto.CompactTextString(m) }
func (*IntermediateResult) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("bacs.problem.single.IntermediateResult_State", IntermediateResult_State_name, IntermediateResult_State_value)
}
