// Code generated by protoc-gen-go.
// source: bacs/problem/single/task.proto
// DO NOT EDIT!

package single

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bacs_problem1 "github.com/bacsorg/problem/go/bacs/problem"
import bacs_process1 "github.com/bacsorg/common/go/bacs/process"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// !
// \brief Task for testing system
type Task struct {
	// !
	// \brief Problem hash.
	//
	// If is not the same as worker's, task is rejected.
	System   *bacs_problem1.System    `protobuf:"bytes,1,opt,name=system" json:"system,omitempty"`
	Solution *bacs_process1.Buildable `protobuf:"bytes,2,opt,name=solution" json:"solution,omitempty"`
	Profile  *bacs_problem1.Profile   `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}

func (m *Task) GetSystem() *bacs_problem1.System {
	if m != nil {
		return m.System
	}
	return nil
}

func (m *Task) GetSolution() *bacs_process1.Buildable {
	if m != nil {
		return m.Solution
	}
	return nil
}

func (m *Task) GetProfile() *bacs_problem1.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}
